-- MySQL Script generated by MySQL Workbench
-- Tue Jan 18 15:24:52 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema userdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema userdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `userdb` DEFAULT CHARACTER SET utf8 ;
USE `userdb` ;

-- -----------------------------------------------------
-- Table `userdb`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `userdb`.`user` ;

CREATE TABLE IF NOT EXISTS `userdb`.`user` (
                                             `id` INT NOT NULL AUTO_INCREMENT,
                                             `lastName` VARCHAR(45) NOT NULL,
    `firstName` VARCHAR(45) NOT NULL,
    PRIMARY KEY (`id`))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `userdb`.`email`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `userdb`.`email` ;

CREATE TABLE IF NOT EXISTS `userdb`.`email` (
                                              `id` INT NOT NULL AUTO_INCREMENT,
                                              `mail` VARCHAR(45) NOT NULL,
    `user_id` INT NOT NULL,
    PRIMARY KEY (`id`, `user_id`),
    INDEX `fk_email_user_idx` (`user_id` ASC) VISIBLE,
    CONSTRAINT `fk_email_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `userdb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `userdb`.`phoneNumber`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `userdb`.`phoneNumber` ;

CREATE TABLE IF NOT EXISTS `userdb`.`phoneNumber` (
                                                    `id` INT NOT NULL AUTO_INCREMENT,
                                                    `number` VARCHAR(45) NOT NULL,
    `user_id` INT NOT NULL,
    PRIMARY KEY (`id`, `user_id`),
    INDEX `fk_phoneNumber_user1_idx` (`user_id` ASC) VISIBLE,
    CONSTRAINT `fk_phoneNumber_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `userdb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
